import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import about from "./about/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "${inter.className} flex flex-col min-h-screen bg-white text-[26px]"
        }
      >
        <header className=" container mx-auto flex justify-between mt-[34px] font-bold">
          <Navigation navlinks={[{ title: "Talk Business", href: "/home" }]} />
          <Navigation
            navlinks={[
              { title: "Home", href: "/home" },
              { title: "About", href: "/about" },
              { title: "Services", href: "/services" },
              { title: "Systems", href: "/systems" },
              { title: "Contact", href: "/contact" },
            ]}
          />
        </header>
        <main className="flex  flex-col  flex-1">{children}</main>
        <footer className=" bg-indigo-950 h-[655px] text-white">
          <div className="container mx-auto justify-between flex">
            <div>
              <h2 className="w-[576px] font-bold text-[58px] text-white pt-[70px] pb-[11px]">
                Let’s start working to build a brighter future.
              </h2>
              <p className="w-[456px] text-[16px] text-white mb-[32px]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Elementum posuere eget elementum vulputate elementum viverra
                sapien tellus aenean.
              </p>
              <ul className="flex gap-6">
                <li>
                  <a href="#"> Fb</a>
                </li>
                <li>
                  <a href="#"> In</a>
                </li>
                <li>
                  <a href="#">Tw</a>
                </li>
                <li>
                  <a href="#">Ln</a>
                </li>
              </ul>
              <h2 className="mt-[120px] font-bold text-[21px]">New Business</h2>
            </div>
            <div>
              <div className="flex justify-between w-[560px] border p-[26px] mt-[176px] ">
                <h3>Join our mailing list</h3>

                <h3>submit</h3>
              </div>
              <p className="mt-[330px] text-right">
                Copyright 2021. All rights reserved.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
